//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeding2019ETL
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_raw_data_Seeding_2019
    {
        public Nullable<int> ts_sec { get; set; }
        public Nullable<int> ts_usec { get; set; }
        public Nullable<byte> channel { get; set; }
        public string mid { get; set; }
        public string pgn { get; set; }
        public string sa { get; set; }
        public Nullable<byte> dlc { get; set; }
        public Nullable<byte> d0 { get; set; }
        public Nullable<byte> d1 { get; set; }
        public Nullable<byte> d2 { get; set; }
        public Nullable<byte> d3 { get; set; }
        public Nullable<byte> d4 { get; set; }
        public Nullable<byte> d5 { get; set; }
        public Nullable<byte> d6 { get; set; }
        public Nullable<byte> d7 { get; set; }
        public int ref_id { get; set; }
    
        public virtual log_meta_data log_meta_data { get; set; }
    }
}
