//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeding2019ETL
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_meta_data
    {
        public int ref_id { get; set; }
        public string file_name { get; set; }
        public string project_name { get; set; }
        public Nullable<System.DateTime> time_pushed { get; set; }
        public Nullable<System.DateTime> log_start_time { get; set; }
        public Nullable<System.DateTime> log_end_time { get; set; }
        public string machine_id { get; set; }
        public Nullable<float> file_size { get; set; }
    
        public virtual can_raw_data_Seeding_2019 can_raw_data_Seeding_2019 { get; set; }
    }
}
